# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_bigger_full.txt --expname restore_embeds_qv_fc_realistic_syndata --n_iters 300000 --i_img 10 --N_rand 256 --i_weights 10
# CUDA_VISIBLE_DEVICES=1 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_defocus_deblurnerf_c1inviewandray --n_iters 200000 --i_img 2000 --N_rand 1024 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_newcorrup_dark_alethnerf --n_iters 30000 --i_img 2000 --N_rand 512 --i_weights 2000 --finetune

# CUDA_VISIBLE_DEVICES=1 python3 -W ignore train.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_dehazenerf_data_auxloss --n_iters 200000 --i_img 2000 --N_rand 256 --i_weights 2000 --finetune

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full_finetune.txt --expname finetune_haze_vgglossmodel --n_iters 50000 --i_img 10000 --N_rand 576 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode center

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_skipcon_model --n_iters 50000 --i_img 5000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel nostrgth_dyndeg_emb_wgt_skipcon --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_base_model --n_iters 50000 --i_img 10000 --N_rand 256 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_haze_yesstrength_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup haze --typeofmodel yesstrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_underwater_vgg_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup underwater --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finetune_underwater_vgg_model --n_iters 50000 --i_img 10000 --N_rand 576 --i_weights 10000 --finetune --ft_corrup underwater --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode center

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_snow_base_model_lessdata --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup snow --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_test_dyn --eval_dataset llff_dyn

# CUDA_VISIBLE_DEVICES=1 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_snow_base_model --n_iters 50000 --i_img 10000 --N_rand 512 --i_weights 10000 --finetune --ft_corrup snow --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn

CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finetune_defocus_finalpaper --n_iters 50000 --i_img 10000 --N_rand 256 --i_weights 1000 --finetune --ft_corrup defocus --typeofmodel nostrgth_dyndeg_emb_wgt --viewtrans_depth 8 --rendtrans_depth 8 --train_dataset llff_test_dyn --eval_dataset llff_test_dyn
