# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 30000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_emb_wgt_novgg --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_noembwgt_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg_patch_vggloss --n_iters 400000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_bigger_full.txt --expname finalpaper_noembwgt_genexpt_dark_haze_rain_motion_burstnoise_nostrgth_dyndeg --n_iters 300000 --N_rand 384 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn 

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_motionblur_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 90000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup motion --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_motionblur_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 90000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup motion --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_motionblur_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 90000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup motion --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_lowlight_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_nostrgth_dyndeg_emb_wgt_patch_vggloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel nostrgth_dyndeg_emb_wgt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg_str.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_5corr_yesstrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb_resnet_strenc_noregloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel yesstrgth_dyndeg_emb_wgt_strenc --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg_str.py --config configs/transibr_bigger_full.txt --expname finalpaper_genexpt_5corr_yesstrgth_dyndeg_emb_wgt_patch_vggloss_withclean_emb_resnet_strenc_noregloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel yesstrgth_dyndeg_emb_wgt_strenc --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode  --


# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg_str.py --config configs/transibr_bigger_full.txt --expname ablation_1corruption --n_iters 70000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel yesstrgth_dyndeg_emb_wgt_strenc --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup dark --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode center --N_samples 64
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg_str.py --config configs/transibr_bigger_full.txt --expname ablation_3corruption --n_iters 50000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel yesstrgth_dyndeg_emb_wgt_strenc --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup threecorr --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode center --N_samples 64

# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_vgg_str.py --config configs/transibr_bigger_full.txt --expname finalpaper_haze_yesstrgth_dyndeg_noregloss --n_iters 200000 --N_rand 324 --i_img 10000 --i_weights 10000 --typeofmodel yesstrgth_dyndeg_emb_wgt_strenc --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup haze --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --sample_mode center --N_samples 64

CUDA_VISIBLE_DEVICES=0 python3 -W ignore train_gnt.py --config configs/transibr_bigger_full.txt --expname vanilla_gnt_all_6corruptions --n_iters 100000 --N_rand 256 --i_img 5000 --i_weights 10000 --typeofmodel gnt --pretrained_allweights --viewtrans_depth 8 --rendtrans_depth 8 --ft_corrup gen --train_dataset llff_dyn+ibrnet_collected_dyn --eval_dataset llff_test_dyn --N_samples 64